In [368]:
# https://realpython.com/pandas-dataframe/#iterating-over-a-pandas-dataframe

import os
os.chdir("C:/Users/Dell/Documents")

import pandas as pd

# Create Dataframe------------------------------------------------------

l = [[1, "Ууганбаяр", 28, "Эр", "Ховд"],
    [2, "Батсүрэн", 23, "Эр", "Улаанбаатар"],
    [3, "Уянга", 44, "Эм", "Улаанбаатар"]]

df = pd.DataFrame(l, columns=['№', 'Нэр', 'Нас', 'Хүйс','Хаяг'])

# Import from Excel------------------------------------------------------
# df = pd.read_excel("Pandas.xlsx")
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0)
# df = pd.read_excel("Pandas.xlsx", sheet_name = 'A')
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0, index_col = 0)
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0, index_col = 0, header = 2)
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0, usecols = 'B,D:F')
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0, skiprows = 2)
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0, skiprows = 2, index_col=0)
# df = pd.read_excel("Pandas.xlsx", sheet_name = 0, header=[0,1,2,3])
df

# Accessing and Modifying Data------------------------------------------------------

# df.columns
# df.columns[1]
# df.index

# df.Нэр
# df['Нэр']
# df.loc[3]
# df.loc[3, 'Хаяг']
# df.loc[:,"Нас"]
# df.iloc[:,5]
# df.loc[2:5,["Нас", "Хүйс"]]
# df.iloc[2:6,[2,3]]
# df.iloc[2:6:2,[2,3]]

# df.at[3,"Хаяг"]
# df.iat[3,5]

# df.loc[:3,'Нас'] = [33,44,55,66]
# df.at[3,"Хаяг"] = "Чойр"

# df.loc[4:,"Нас"] = 0

# df.loc[df.Хаяг == "Улаанбаатар", "Хаяг"] = "УБ Хот"

# df
# Inserting and Deleting Columns, Rows------------------------------------------------------

# df['score'] = 0

# df['score'] = [11,12,14,15,'',18,21]

# del df['score']
# df.pop('score')

# a=len(df.index)+1
# df.loc[a] = [a-1,"Батжаргал", 47, "Эр", "","Зүүнхараа",27]
# df.drop(df.index[8])

# df.to_excel('try1.xlsx')

# Applying Arithmetic Operations------------------------------------------------------
# df['Нас'] + df['score']
# df['Total'] = df['Нас'] + df['score']

# df.to_excel('try1.xlsx')

# Sorting a Pandas DataFrame------------------------------------------------------

# df.sort_values(by='Total', ascending=False)
# df.sort_values(by=['Total', 'Нэр'], ascending=[False, False])

# Filtering Data------------------------------------------------------

# filter_ = df['score'] >= 18
# filter_
# df[filter_]
# df

# df[['score', 'Нас']] = df[['score', 'Нас']].apply(pd.to_numeric)
# print(df.dtypes)

# df[(df['Нас'] >= 18) & (df['score'] >= 13)]

# Handling Missing Data------------------------------------------------------

# df.dropna(how = 'all', axis = 1)
# # df.dropna(how = '.', axis = 0, )

# df.fillna("hello")
# df.fillna(method='bfill')

   №        Нэр  Нас Хүйс         Хаяг
0  1  Ууганбаяр   28   Эр         Ховд
1  2   Батсүрэн   23   Эр  Улаанбаатар
2  3      Уянга   44   Эм  Улаанбаатар